### ISSUE TITLE
[BUG] - No separators for Dart's asynchronous generators

### ISSUE THREAD

**Issue by JCKodel** [alefragnani/vscode-separators#105]
**Environment/version**

- Extension version: 2.7.0
- VSCode version: 1.95.3
- OS version: MacOS Sequoia 15.1

**Steps to reproduce**

Create a asynchronous generator get accessor in Dart:

```dart
@override
void postInitState(BuildContext context) {
}

@override
Stream<AppState> get stream async* {
}
```

The separator won't appear over the async generator (the selected bit):

<img width="481" alt="image" src="https://github.com/user-attachments/assets/234d2aac-3968-4f8c-8bc9-869ca6f692a8">

**Comment by alefragnani** [comment]
Hi @JCKodel ,

Are asynchronous generators available as separate functions/symbols in the `Outline` view? Can you navigate to it, using <kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>O</kbd>?

The Separators extension uses the language extension as the source of symbols. So, if it is not drawing a separator on this asynchronous generators, I suppose the Dart language extension doesn't recognize them as regular functions.

Hope this helps

**Comment by JCKodel** [comment]
> Are asynchronous generators available as separate functions/symbols in the Outline view?

<img width="426" alt="image" src="https://github.com/user-attachments/assets/c9b9f1c3-9647-4164-ada6-a948c5f07b63">

Yes.

>  Can you navigate to it, using Cmd + Shift + O?

I don't know what Cmd+Shift+0 does (my VSCode doesn't have that bind, not even if I delete all custom bindings).

But the breadcrumb shows it:

<img width="557" alt="image" src="https://github.com/user-attachments/assets/fb9756f4-5f06-4ff8-9317-c1076ef5ef04">

**Comment by alefragnani** [comment]
If you are using Windows or Linux, it may be <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>O</kbd>. It is the `Go to Symbol in Editor...` command.

The 🔧 icon means the the asynchronous generator is not recognized as a _function_ or _method_, but a `property`. And `properties` has no separators today. It seems Dart has the same approach as JS, and other languages, like Delphi, C#, and so on. 

There is already an issue asking for that https://github.com/alefragnani/vscode-separators/issues/38. Feel free to upvote, and provide more Dart samples, if possible.

Hope this helps

**Comment by JCKodel** [comment]
Changing `Stream<AppState> get stream async* {}` to `Stream<AppState> stream async* {}` "solves" the issue (the change is to remove the `get`).

So, no new issue (properties the issue, not async generators)
