### ISSUE TITLE
[FEATURE] - Make `separators.enabledSymbols` setting customizable _per language_

### ISSUE THREAD

**Issue by ctf0** [alefragnani/vscode-separators#18]
when working with `sass,css` the separators are very distracting, is it possible to add a new config to disable the ext for specific languages ?

**Comment by alefragnani** [comment]
Hi @ctf0 ,

I thought about that myself while testing the extension on different languages I use, but decided to keep it simple, at start.

 I just wonder the best approach for that. 

* A simple `enabledLanguages` setting, to disable specific languages
* A more complex _language related setting_ where the user could define different settings for each language (https://code.visualstudio.com/docs/getstarted/settings#_languagespecific-editor-settings)

Thanks for reporting

**Comment by ctf0** [comment]
> A more complex language related setting where the user could define different settings for each language

i actually thought about that when i was creating the ticket, but i think its better to keep it simple at first, at least untill the extension get some momentum.

**Comment by alefragnani** [comment]
Just an update about this feature. 

I learned a bit more about the topic, and it seems the _per language _ setting is not that complex to make, nor use. The setting _can be_ per language, but is up to the user to choose how to update the setting, globally or individually.

I’ll dig a bit more about it while doing #33 , and if it confirmed, both issues could land on the next release.

**Comment by alefragnani** [comment]
Instead of **disabling the extension** for specific languages, I'll make the `separators.enabledSymbols` setting to be **per language**. 

Doing so, you will be able to customize / disable the separators on a language basis:

```json
    // the default value, when all symbols are enabled for every language
    "separators.enabledSymbols": [
        "Classes",
        "Constructors",
        "Enums",
        "Functions",
        "Interfaces",
        "Methods",
        "Namespaces"
    ],

    // choose specific symbols for typescript 
    "[typescript]": {
        "separators.enabledSymbols": [
            "Enums",
            "Interfaces"
        ],
    },
    // choose a different set of symbols for javascript
    "[javascript]": {
        "separators.enabledSymbols": [
            "Functions"
        ],
    },
```

Stay tuned

**Comment by ctf0** [comment]
can we make `separators.enabledSymbols` accept empty array so we can disable it completely for a language ?

**Comment by alefragnani** [comment]
It already works 😬 

You can simply ignore the warning (orange wave line) while customizing User Settings. I remove the limitation in the `Separators: Select Symbols` command, but forgot the user setting definition.

It should fixed in a patch in a couple of days.

Thanks for reporting
