### ISSUE TITLE
"double"  option visible only with width 3 or more

### ISSUE THREAD

**Issue by burcaka** [alefragnani/vscode-separators#19]
"separators.constructors.borderStyle": "double"

produces a single, solid line in my case. The other options (solid, dotted, dashed) work fine.

Also changed "separators.classes.borderWidth" to various values (1, 2, 3, 4) to make sure that this is not a "can't see the double line because of the thickness" issue.

Observed on macOS 10.15.7 and  VS Code 1.51.1.

**Comment by alefragnani** [comment]
Hi @burcaka ,

Sure, the `double` style won't be visible for `width` `1` or `2`, but starting with `3`, they should appear.

This is from my system, the same config as yours, running on a Mac mini.

![Screen Shot 2020-11-26 at 12 04 17](https://user-images.githubusercontent.com/3781424/100366504-a6591300-2fdf-11eb-9213-59d1b2cddbc8.png)

Could you provide more details?

**Comment by burcaka** [comment]
At "borderWidth" 3, they do become barely visible and at 4, they are pretty visible. You are right. I must have made a mistake somewhere while testing.

Please consider the issue resolved.
