### ISSUE TITLE
[FEATURE] - Add separators for more symbols

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-separators#2]
More symbols could have their own separators.

- [x] Class
- [x] Interface
- [x] Enum
- [x] Namespace

Please, suggest/vote 😬 

Here you can find all kinds of symbols supported by VS Code, and that each language extension must provides/adapt: https://code.visualstudio.com/api/references/vscode-api#SymbolKind

**Comment by JCKodel** [comment]
I've opened the https://github.com/alefragnani/vscode-separators/issues/7 regarding Dart constructions (it works only on methods or constructors).

Basically, all "class-like" (class, interface, enum, mixin, extension), all methods (get/set accessors, methods, constructors).

If each group could have its own color would be amazing.

**Comment by JCKodel** [comment]
Please, add support for `Namespace` because of this: https://github.com/Dart-Code/Dart-Code/issues/2945#issuecomment-724846211
