### ISSUE TITLE
[FEATURE] - Configure depth of separators rendered

### ISSUE THREAD

**Issue by colelawrence** [alefragnani/vscode-separators#24]
I would appreciate being able to configure the level at which the separators are going to be rendered (especially on a language by language basis)

For many very dense files such as in type definitions (without impls), there can end up being a plethora of separators which can become distracting since I do not necessarily want functions to render differently than properties (properties are not decorated).

![image](https://user-images.githubusercontent.com/2925395/110354111-cdbf7300-8005-11eb-93b0-65eb80199778.png)

In this screenshot, we see this inner function being highlighted, but it feels very out of place to me in my personal preference. I feel like I would be happy if I could configure the level of the symbols which separators can actually decorate (so say for TypeScript: max level 0 while in Rust: no max level).

Let me know what you think!

Thanks

**Comment by alefragnani** [comment]
Hi @colelawrence ,

I had this need right after releasing the extension, for some of the projects I use. No only for _depth_ but `callbacks` as well (which I filled #33 right now).

I’m planning both issues to the next release.

Thank you
