### ISSUE TITLE
[FEATURE] - Add separators only if the symbol body has at least N lines

### ISSUE THREAD

**Issue by alefragnani** [alefragnani/vscode-separators#3]
Based on [this comment](https://github.com/microsoft/vscode/issues/56530#issuecomment-434915287) from the original issue on VS Code repo

> [ ] show separator before class definition
[ ] show separator before function definition
   |----[ ] show separator if function body is at least [ 3 ] lines long
[ ] show separator before class method definition
   |----[ ] show separator if class method's body is at least [ 3 ] lines long

**Comment by softopti** [comment]
My request was to exclude separator in c++ class for one liner or declaration, but I think that this request can fulfill my need.
If there are multiple one liner, that will be nice to get a separator before the first one.

**Comment by alefragnani** [comment]
Hi @softopti ,

First of all, sorry for the late reply.

About the original feature, it wound't fulfill exactly as you ask, as it would not add any separator on any of those symbols, as all of them will have the same amount of lines.

I think that your case (**C++**) is similar to the one I already thought adding for my **Pascal** source files. Since both languages has _declaration sections_ (Pascal are located within the implementation ), the separators are overcrowded on that section. Maybe a new setting to  _ignore declaration symbols/sections_

Hope this helps
