### ISSUE TITLE
[FEATURE] - improve description for searching

### ISSUE THREAD

**Issue by sheldonhull** [alefragnani/vscode-separators#44]
I had a really hard time finding the extension after resetting my extension list. 

I searched for roughly 5 mins and only found by chance because i had enabled in one project.

Please consider improving the description for those looking for:

- section divider
- sections
- line delimiter
- section lines

I think that might help more find this extension. I've found it a nice little UI enhancement so want others to be able to find it 👍🏻 

thank you!

**Comment by alefragnani** [comment]
Hi @sheldonhull ,

I’m sorry to hear you had difficulties to find the extension. Just out of curiosity, which UI did you use? The Extension view inside VS Code, or VS Code Marketplace webpage?

There are a few complains about the marketplace search engine (on VS Code repo), where extensions aren’t properly sorted by relevance, but I can’t say when this will be fixed/updated by the marketplace team.

I’ve noticed you send a PR. We can discus the improvements there.

Thank you

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if you still wants to contribute.

Thanks for your understanding
