### ISSUE TITLE
[FEATURE] -  overrides for Go/Golang based interfaces

### ISSUE THREAD

**Issue by onedealcc** [alefragnani/vscode-separators#47]
It  would be nice when using the plugin on Go projects to be able to set a separator for the interface but not all the func sigs contained in the interface, but have them for the implementation of the functions elsewhere (so not as simple as disabling)

**Comment by alefragnani** [comment]
Hi @edleoncc ,

Could you please provide a mockup/print with more details about what you are trying to achieve? Better yet if your mockup shows how the extension works (or does not work) today, and how you think it should work.

Thanks in advance

**Comment by alefragnani** [comment]
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding
