### ISSUE TITLE
[BUG] - Put the separator abobe jsdoc

### ISSUE THREAD

**Issue by zuhairtaha** [alefragnani/vscode-separators#48]
**Environment/version**

- Extension version: 2.2
- VSCode version: 1.59.0
- OS version: Windows 10

**Steps to reproduce**

1. Just write any function, method, or class adding [jsdoc](https://jsdoc.app/)
Example
```js
/**
 * @param {number} a
 * @param {number} b
 * @return {number}
 */
function add(a, b) {
  return a + b;
}

/** @return {string} */
function sayHello() {
  return "Hello";
}

/**
 * @example
 * const a = new A();
 */
class A {
  /**
   * @return {number}
   */
  method() {
    return 1;
  }
}

```
![image](https://i.imgur.com/VAiNsmr.png)

Lines should be above the jsdoc annotations

**Comment by alefragnani** [comment]
Hi @zuhairtaha ,

The extension is designed this way, and the same requeste has already been made in #21 .

To better understand how/why it works this way, this is the comment I added to another request made before, in #8:

> The extension uses the VS Code/extensions engine to detect the Symbols (Methods, Functions and Constructors). Doing so, location it uses to draw the lines, depends entirely on these engines. I don’t do any kind of parsing on the source code. And Comments, is not a SymbolKind supported by VS Code.

You can confirm the location if you use `Go to Symbol` or the `Outline` panel. When you select some Symbol, it won't put the cursor at the beginning of the jsdoc, but at the class/function, just like the separator.

Hope this helps

**Comment by zuhairtaha** [comment]
Thank you @alefragnani 
That makes sense. Just I asked because this is how it looks at WebStorm where I migrated from.
Anyway relaying on vscode symbols without parsing will make it work 100% in the correct place (regardless jsdocs)
