### ISSUE TITLE
[FEATURE] - Ability to manually add separator lines

### ISSUE THREAD

**Issue by coffincw** [alefragnani/vscode-separators#49]
Would it be possible to add a feature to be able to right-click on a location in any opened file to add a separator line just like the ones automatically placed within compatible code files?

Thanks!

**Comment by alefragnani** [comment]
Hi @coffincw ,

Thanks for your suggestion, but I think this is out of scope. The extension’s idea is to draw separators on _source symbols_, as a way make the source more readable. Not for the user to create sections/separations to make its own organization.

But, I remember seeing another extension which could work for you. It’s called [Line Highlight Bookmark](https://marketplace.visualstudio.com/items?itemName=balmacefa.linehighlightbookmarkvscode). 

Hope this helps
