### ISSUE TITLE
[FEATURE] - Lua - separators.functions.ignoreCallbackInline

### ISSUE THREAD

**Issue by CarlosLeyvaAyala** [alefragnani/vscode-separators#50]
Hi.
I'd like to ask if it is possible to add support for Lua for the `functions.ignoreCallbackInline` setting.

Here are some sample functions with inlines:

![separators-inline-lua](https://user-images.githubusercontent.com/64770846/130286529-67108f39-8302-48ad-8059-b08017a3d2d9.png)

And their respective structure in the outline:

![separators-inline-lua-outline](https://user-images.githubusercontent.com/64770846/130286614-f440866d-becd-4d11-9afa-eaf2b4b62a76.png)

**Comment by alefragnani** [comment]
Hi @CarlosLeyvaAyala ,

Could you please update the outline picture with the _whole line content_, so I could better understand how VS Code/Lua Language Server describes a `callback` function?

Thanks in advance

**Comment by CarlosLeyvaAyala** [comment]
Like this?

![2021-08-22 13_30_25-__test lua](https://user-images.githubusercontent.com/64770846/130366220-5d9e365a-446b-4b7d-a3ae-0e6e3936b831.png)

BTW, I also found some kinda real code that use more inline anonymous functions that get detected.
I hope this also helps :)


![2021-08-22 13_31_21](https://user-images.githubusercontent.com/64770846/130366328-152a4a18-cb94-470a-8df1-72c3f7dafc38.png)

![2021-08-22 13_33_28-__test lua](https://user-images.githubusercontent.com/64770846/130366307-e8b34453-5a3c-4a1c-bb5a-baa3b4f106e3.png)

**Comment by alefragnani** [comment]
I guess so 😄 

Only those described as `<Anonymous>`, with a `-> function` detail are Callback Inline, right?

**Comment by CarlosLeyvaAyala** [comment]
There's also a named inline function called `me2` in the second screen I took (typo), but correctly named `meh2` in my first message. It belongs to `meh`:

![meh2](https://user-images.githubusercontent.com/64770846/130366220-5d9e365a-446b-4b7d-a3ae-0e6e3936b831.png)

That function is the equivalent to having a `void => void` signature, or something; that's why it's so easy to overlook.

**Comment by alefragnani** [comment]
But this one is not a `callback` right? It seems just an inline/anonymous declaration. 

I never worked with Lua, so I can't say for sure. I'm just comparing to other languages I play with.

**Comment by CarlosLeyvaAyala** [comment]
That's right. It's not a callback.

In Lua all functions that can be declared both as a variable and as a function statement:

![2021-08-24 15_00_56-__test lua - Max-Sick-Gains-src - Visual Studio Code](https://user-images.githubusercontent.com/64770846/130682197-e9dc0609-250f-4868-9333-b876f9496cb9.png)

![2021-08-24 15_14_04-](https://user-images.githubusercontent.com/64770846/130683593-8ca99ea2-a524-438b-973f-4bd96a20c4ed.png)

Those functions can only be used inside the function where it were defined, as expected.
Look at how this is actually complaining that `inlineVoid` hasn't been defined:

![2021-08-24 15_16_31-__test lua - Max-Sick-](https://user-images.githubusercontent.com/64770846/130683948-62b97b80-9612-42bf-9be8-3d5a180b4938.png)

If I take out that problematic line and run the code above, I get this:

```
Printed	5
Anon printed	5
Printed	5
Anon printed	15
Printed	5
Anon printed	25

When you evaluate the resulting anonymous function:
Result print	5
```

I could have declared all those inlines in a single line like I did with `addAnon`, by the way.
Sadly  (fortunately to you, so you don't have to take so many cases into account? xD), in vanilla Lua there's nothing like lambda notation, "fat arrows", or whatever, to make one liners more succint.
If you want to declare a one line function, it ought to have the whole body declaration, like this:

```Lua
function OneLiner() end
OneLinerAnon = function() end
```

**Comment by alefragnani** [comment]
That's great!

BTW, which Lua extension are you using, and how it does identify Lua files? Simply `lua`? 

I need to know this, to properly identify the files and to filter the symbols.

Thank you

**Comment by CarlosLeyvaAyala** [comment]
I use [Lua](https://marketplace.visualstudio.com/items?itemName=sumneko.lua).

I'm not sure how it recognizes files, other than the `*.lua` extension.
As far as I know, that's the only extension for Lua files and searching for other extensions gave me nothing.

BTW, I'm the one that should thank you for your patience.

**Comment by alefragnani** [comment]
It's not the file extension, but how the extension declares the language Id (`lua`). Looking at extension's source I'm able to find.

I don't have a setup to try out, but I hope the details you provided (and my interpretation) will be enough. It should be available next month, right after VSCode release.

> BTW, I'm the one that should thank you for your patience.

Thank you too for providing the details. Without that, the feature wouldn't be released (at least, not by me) 😬

Thank you

**Comment by CarlosLeyvaAyala** [comment]
Thank you so much!
If more info is needed, I hope I can provide it. Don't hesitate to ask me.

**Comment by alefragnani** [comment]
Let's hope it works out of the box, otherwise will be you asking me, for a fix 😆 

It should be available next week. 

Stay tuned

**Comment by ypnos** [comment]
I tried this option and unfortunately, it seems it doesn't do the trick for me:

![image](https://user-images.githubusercontent.com/8481470/132236016-357e8ebf-1263-4b48-acf2-427184a8be66.png)

Purple lines are from Separators plugin v2.3.0. The setting is set:
```json
    "separators.functions.ignoreCallbackInline": true,
```

**Comment by alefragnani** [comment]
Hi @ypnos ,

As described in the comment above (https://github.com/alefragnani/vscode-separators/issues/50#issuecomment-903334676) these are not considered _callbacks_. 

These ones are just inline/anonymous functions.

Hope this helps

**Comment by ypnos** [comment]
Ok so I just misunderstood, I thought "ignoreCallbackInline" means "ignore callback and inline". I understand it better now.

Here is example code to confirm that it works:
![image](https://user-images.githubusercontent.com/8481470/132262480-83489dd5-a746-4446-a704-d8c8a6191c4e.png)

**Comment by alefragnani** [comment]
No problem. If you misunderstood, it means the setting is not so clear, and the documentation needs improvement.

Anyway, if you miss the possibility to ignore `inline`/`anonymous` functions, this could be accomplished with a new setting. Feel free to open a new issue for that, providing the details to identify/differentiate `inline` / `anonymous` functions.

Hope this helps

**Comment by alefragnani** [comment]
BTW, thank you for the confirmation the current setting is working 👍
