### ISSUE TITLE
[FEATURE] - add separator above comment related to func but sitting on top of declaration

### ISSUE THREAD

**Issue by irisida** [alefragnani/vscode-separators#8]
Not idiomatic in all code guides but its not uncommon for a comment to be outside/ontop the func signature. 
It would be nice to be abe to have the separators include that. (configurable maybe?)

**current example**

```
// some comment text
------------------------------------
func name(sig) {
}
```

**desired sample**
```
------------------------------------
// some comment text
func name(sig) {
}
```

Given it's not correct for all languages it might be better as a boolean option or something. Anyway, thanks for reading/considering.

**Comment by alefragnani** [comment]
Hi @irisida ,

The extension uses the VS Code/extensions engine to detect the `Symbols` (`Methods`, `Functions` and `Constructors`). Doing so, _location_ it uses to draw the lines, depends entirely on these engines. I don’t do any kind of parsing on the source code. And `Comments`, is not a `SymbolKind` supported by VS Code.

To support this feature, parsing is mandatory. I know a few programming languages, and I remember different syntax for comments on each of them. So, in fact, it would require a few parsers. 

Hope this helps

**Comment by irisida** [comment]
Makes sense. Would be a bit ask and add overhead and flakiness at an early evolution. closing issue.
