### ISSUE TITLE
[FEATURE] - Change all settings at once

### ISSUE THREAD

**Issue by TheCarpetMerchant** [alefragnani/vscode-separators#85]
Not sure if VSCode allows this, but being able to settings for each type of line at once would be great, for now I'm changing the settings file directly :')

Very nice extension, thanks for the work man 👍

**Comment by alefragnani** [comment]
Hi @TheCarpetMerchant ,

I'm not sure what you mean about "each type of line at once", but the Settings UI has no _bulk edit_ so, each setting must be updated independently. If you need something more flexible yes, the JSON editor and its multi cursor support is your friend.

Hope this helps

**Comment by TheCarpetMerchant** [comment]
Oh well, one day hopefully. Thanks :)
