### ISSUE TITLE
[APPRECIATION] - Thank you for this extension!

### ISSUE THREAD

**Issue by vadviktor** [alefragnani/vscode-separators#90]
I only wanted to publicly thank you @alefragnani for this wonderful extension. This is a feature I'm missing since I've ditched Jetbrains products for VSCode. Thank you so much! 🙏 ❤️ 👏

**Comment by alefragnani** [comment]
Hi @vadviktor ,

Thank you for your kind words! I’m glad to know the extension is being helpful.
